{
    "meta": {
        "page": 1,
        "pages": 1,
        "perpage": -1,
        "total": 1000,
        "sort": "asc",
        "field": "RecordID"
    },
    "data": [
        {
            "ID": 1,
            "Name": "Felicia Gisbye",
            "Company": "Tagtune",
            "Phone": "(526) 4906446",
            "Address1": "180 8th Road",
            "Address2": "46 Fair Oaks Plaza",
            "City": "Santo Ni\u00f1o",
            "Country": "Philippines",
            "Postcode": "6711",
            "Type": 3,
            "Status": 3,
            "DateCreated": "11\/20\/2018",
            "DateModified": "12\/22\/2018",
            "Position": 4,
            "ClientState": 3
        },
        {
            "ID": 672,
            "Name": "Bar Richemond",
            "Company": "Dabjam",
            "Phone": "(839) 7324517",
            "Address1": "70253 Hoepker Parkway",
            "Address2": "99 Scoville Plaza",
            "City": "Kundung",
            "Country": "Indonesia",
            "Type": 3,
            "Status": 1,
            "DateCreated": "5\/26\/2018",
            "DateModified": "10\/14\/2018",
            "Position": 2,
            "ClientState": 1
        },
        {
            "ID": 660,
            "Name": "Veda Westbury",
            "Company": "Mybuzz",
            "Phone": "(867) 3792243",
            "Address1": "5 Nova Park",
            "Address2": "29061 Kedzie Street",
            "City": "Belo Horizonte",
            "Country": "Brazil",
            "Postcode": "30000-000",
            "Type": 3,
            "Status": 1,
            "DateCreated": "8\/18\/2018",
            "DateModified": "6\/30\/2018",
            "Position": 1,
            "ClientState": 1
        },
        {
            "ID": 661,
            "Name": "Fionna Hutchcraft",
            "Company": "Kwilith",
            "Phone": "(942) 4852665",
            "Address1": "8831 Leroy Junction",
            "Address2": "52 Southridge Crossing",
            "City": "Byczyna",
            "Country": "Poland",
            "Postcode": "46-220",
            "Type": 3,
            "Status": 1,
            "DateCreated": "3\/16\/2019",
            "DateModified": "4\/4\/2019",
            "Position": 3,
            "ClientState": 2
        },
        {
            "ID": 662,
            "Name": "Enos Pillans",
            "Company": "Topicblab",
            "Phone": "(667) 2141555",
            "Address1": "4024 Lakewood Plaza",
            "Address2": "7851 Comanche Plaza",
            "City": "Yongfeng",
            "Country": "China",
            "Type": 4,
            "Status": 3,
            "DateCreated": "9\/10\/2018",
            "DateModified": "5\/6\/2018",
            "Position": 6,
            "ClientState": 3
        },
        {
            "ID": 663,
            "Name": "Anneliese Duly",
            "Company": "Twimm",
            "Phone": "(193) 8263200",
            "Address1": "4 Laurel Circle",
            "Address2": "3 Grim Street",
            "City": "Quxi",
            "Country": "China",
            "Type": 2,
            "Status": 1,
            "DateCreated": "12\/15\/2018",
            "DateModified": "3\/5\/2019",
            "Position": 4,
            "ClientState": 4
        },
        {
            "ID": 664,
            "Name": "Alyce Wild",
            "Company": "Quinu",
            "Phone": "(862) 3191672",
            "Address1": "486 John Wall Hill",
            "Address2": "941 Ryan Alley",
            "City": "Pleiku",
            "Country": "Vietnam",
            "Type": 3,
            "Status": 3,
            "DateCreated": "12\/17\/2018",
            "DateModified": "12\/12\/2018",
            "Position": 5,
            "ClientState": 4
        },
        {
            "ID": 665,
            "Name": "Luce Brownell",
            "Company": "Topdrive",
            "Phone": "(387) 3905663",
            "Address1": "15901 Warrior Point",
            "Address2": "4021 Cody Circle",
            "City": "Watangan",
            "Country": "Indonesia",
            "Type": 3,
            "Status": 2,
            "DateCreated": "3\/8\/2019",
            "DateModified": "4\/20\/2018",
            "Position": 2,
            "ClientState": 4
        },
        {
            "ID": 666,
            "Name": "Lucien Bonnaire",
            "Company": "Leexo",
            "Phone": "(290) 8057581",
            "Address1": "9757 Manley Center",
            "Address2": "44337 Melrose Avenue",
            "City": "Tal\u0101",
            "Country": "Egypt",
            "Type": 1,
            "Status": 2,
            "DateCreated": "11\/6\/2018",
            "DateModified": "12\/17\/2018",
            "Position": 2,
            "ClientState": 4
        },
        {
            "ID": 667,
            "Name": "Augustus Kobes",
            "Company": "Skimia",
            "Phone": "(575) 2974482",
            "Address1": "5129 Grayhawk Crossing",
            "Address2": "7 Randy Parkway",
            "City": "Santa Cruz de Barahona",
            "Country": "Dominican Republic",
            "Postcode": "11005",
            "Type": 2,
            "Status": 3,
            "DateCreated": "3\/10\/2019",
            "DateModified": "8\/9\/2018",
            "Position": 4,
            "ClientState": 3
        },
        {
            "ID": 668,
            "Name": "Vanna McKean",
            "Company": "Blogpad",
            "Phone": "(484) 4087552",
            "Address1": "2 Fordem Lane",
            "Address2": "0 Daystar Circle",
            "City": "Reading",
            "State": "Pennsylvania",
            "Country": "United States",
            "Postcode": "19610",
            "Type": 1,
            "Status": 3,
            "DateCreated": "11\/9\/2018",
            "DateModified": "5\/7\/2018",
            "Position": 5,
            "ClientState": 1
        },
        {
            "ID": 669,
            "Name": "Rab Dziwisz",
            "Company": "Kwideo",
            "Phone": "(395) 7315295",
            "Address1": "9508 Butterfield Point",
            "Address2": "4 Straubel Alley",
            "City": "Lebedyn",
            "Country": "Ukraine",
            "Type": 4,
            "Status": 1,
            "DateCreated": "5\/21\/2018",
            "DateModified": "7\/18\/2018",
            "Position": 1,
            "ClientState": 1
        },
        {
            "ID": 670,
            "Name": "Joyann Thebeau",
            "Company": "Skidoo",
            "Phone": "(854) 4707492",
            "Address1": "97982 Bartillon Drive",
            "Address2": "88452 Hermina Parkway",
            "City": "Vi\u0161njevac",
            "Country": "Croatia",
            "Postcode": "43226",
            "Type": 2,
            "Status": 3,
            "DateCreated": "2\/22\/2019",
            "DateModified": "5\/27\/2018",
            "Position": 1,
            "ClientState": 3
        },
        {
            "ID": 671,
            "Name": "Almeta Fontell",
            "Company": "Quinu",
            "Phone": "(932) 1810945",
            "Address1": "9903 Del Sol Hill",
            "Address2": "3 Amoth Park",
            "City": "Basa",
            "Country": "Indonesia",
            "Type": 3,
            "Status": 2,
            "DateCreated": "1\/1\/2019",
            "DateModified": "3\/2\/2019",
            "Position": 1,
            "ClientState": 6
        },
        {
            "ID": 673,
            "Name": "Chrissy Koppes",
            "Company": "Zoovu",
            "Phone": "(657) 5854301",
            "Address1": "45618 Elka Junction",
            "Address2": "9559 Reinke Crossing",
            "City": "Cluny",
            "Country": "Mauritius",
            "Type": 4,
            "Status": 1,
            "DateCreated": "7\/18\/2018",
            "DateModified": "10\/16\/2018",
            "Position": 3,
            "ClientState": 6
        },
        {
            "ID": 658,
            "Name": "Chancey Dunthorn",
            "Company": "Viva",
            "Phone": "(860) 6908445",
            "Address1": "1 Ronald Regan Court",
            "Address2": "25127 Barnett Terrace",
            "City": "Avignon",
            "State": "Provence-Alpes-C\u00f4te d'Azur",
            "Country": "France",
            "Postcode": "84007 CEDEX 1",
            "Type": 3,
            "Status": 1,
            "DateCreated": "4\/14\/2019",
            "DateModified": "8\/4\/2018",
            "Position": 2,
            "ClientState": 6
        },
        {
            "ID": 674,
            "Name": "Dasi Cheeke",
            "Company": "Zoonoodle",
            "Phone": "(261) 9035567",
            "Address1": "52 Packers Alley",
            "Address2": "864 Meadow Valley Park",
            "City": "Marina",
            "Country": "Croatia",
            "Postcode": "21222",
            "Type": 2,
            "Status": 3,
            "DateCreated": "12\/16\/2018",
            "DateModified": "2\/19\/2019",
            "Position": 6,
            "ClientState": 1
        },
        {
            "ID": 675,
            "Name": "Urson Cluckie",
            "Company": "Trudoo",
            "Phone": "(915) 5548701",
            "Address1": "591 Pawling Center",
            "Address2": "479 Bunker Hill Street",
            "City": "Isla Puc\u00fa",
            "Country": "Paraguay",
            "Type": 1,
            "Status": 3,
            "DateCreated": "10\/25\/2018",
            "DateModified": "2\/9\/2019",
            "Position": 3,
            "ClientState": 2
        },
        {
            "ID": 676,
            "Name": "Kevan Chitter",
            "Company": "Jayo",
            "Phone": "(310) 4678428",
            "Address1": "4071 Leroy Place",
            "Address2": "09 Division Center",
            "City": "Al Azraq ash Sham\u0101l\u012b",
            "Country": "Jordan",
            "Type": 3,
            "Status": 2,
            "DateCreated": "7\/15\/2018",
            "DateModified": "7\/31\/2018",
            "Position": 6,
            "ClientState": 6
        },
        {
            "ID": 677,
            "Name": "Hercules Cruse",
            "Company": "Skimia",
            "Phone": "(610) 1252928",
            "Address1": "65571 Alpine Center",
            "Address2": "5 Stang Road",
            "City": "Nikol\u2019sk",
            "Country": "Russia",
            "Postcode": "161469",
            "Type": 4,
            "Status": 2,
            "DateCreated": "8\/7\/2018",
            "DateModified": "6\/22\/2018",
            "Position": 1,
            "ClientState": 6
        },
        {
            "ID": 678,
            "Name": "Forest Chateau",
            "Company": "Edgetag",
            "Phone": "(276) 2602360",
            "Address1": "770 Packers Center",
            "Address2": "0526 Maryland Lane",
            "City": "Mino",
            "Country": "Japan",
            "Postcode": "709-4306",
            "Type": 4,
            "Status": 3,
            "DateCreated": "12\/5\/2018",
            "DateModified": "3\/24\/2019",
            "Position": 6,
            "ClientState": 5
        },
        {
            "ID": 679,
            "Name": "Ruby Agg",
            "Company": "Thoughtsphere",
            "Phone": "(288) 4303994",
            "Address1": "12 Rowland Hill",
            "Address2": "6781 Schurz Hill",
            "City": "Bechyn\u011b",
            "Country": "Czech Republic",
            "Postcode": "391 65",
            "Type": 3,
            "Status": 2,
            "DateCreated": "9\/3\/2018",
            "DateModified": "9\/7\/2018",
            "Position": 3,
            "ClientState": 4
        },
        {
            "ID": 680,
            "Name": "Edouard Ringwood",
            "Company": "Jayo",
            "Phone": "(104) 3922011",
            "Address1": "33660 Sunbrook Lane",
            "Address2": "068 Grim Pass",
            "City": "Oslo",
            "State": "Oslo",
            "Country": "Norway",
            "Postcode": "0216",
            "Type": 2,
            "Status": 1,
            "DateCreated": "5\/13\/2018",
            "DateModified": "9\/26\/2018",
            "Position": 6,
            "ClientState": 6
        },
        {
            "ID": 681,
            "Name": "Guillema Pray",
            "Company": "Voolia",
            "Phone": "(312) 1911371",
            "Address1": "581 Shasta Lane",
            "Address2": "09796 Little Fleur Crossing",
            "City": "Luthu",
            "Country": "Indonesia",
            "Type": 1,
            "Status": 1,
            "DateCreated": "11\/21\/2018",
            "DateModified": "10\/9\/2018",
            "Position": 1,
            "ClientState": 6
        },
        {
            "ID": 682,
            "Name": "Cecilia Haucke",
            "Company": "Avamm",
            "Phone": "(668) 5395991",
            "Address1": "10 Truax Hill",
            "Address2": "10 Lindbergh Crossing",
            "City": "Taishang",
            "Country": "China",
            "Type": 2,
            "Status": 2,
            "DateCreated": "12\/25\/2018",
            "DateModified": "12\/29\/2018",
            "Position": 4,
            "ClientState": 4
        },
        {
            "ID": 683,
            "Name": "Archer Joynson",
            "Company": "Agivu",
            "Phone": "(234) 1084491",
            "Address1": "8160 Florence Street",
            "Address2": "4159 Prairie Rose Street",
            "City": "Jeju-si",
            "Country": "South Korea",
            "Type": 4,
            "Status": 1,
            "DateCreated": "12\/26\/2018",
            "DateModified": "7\/30\/2018",
            "Position": 4,
            "ClientState": 1
        },
        {
            "ID": 684,
            "Name": "Celina Niland",
            "Company": "Gigazoom",
            "Phone": "(464) 7533829",
            "Address1": "81197 Mallard Trail",
            "Address2": "9740 Orin Parkway",
            "City": "Zheleznogorsk-Ilimskiy",
            "Country": "Russia",
            "Postcode": "665654",
            "Type": 2,
            "Status": 1,
            "DateCreated": "3\/12\/2019",
            "DateModified": "4\/11\/2019",
            "Position": 5,
            "ClientState": 5
        },
        {
            "ID": 685,
            "Name": "Pasquale Jessep",
            "Company": "Kanoodle",
            "Phone": "(280) 8583751",
            "Address1": "8074 Laurel Point",
            "Address2": "1205 Huxley Court",
            "City": "Kudus",
            "Country": "Indonesia",
            "Type": 1,
            "Status": 2,
            "DateCreated": "6\/13\/2018",
            "DateModified": "12\/18\/2018",
            "Position": 3,
            "ClientState": 2
        },
        {
            "ID": 686,
            "Name": "Laraine Daulton",
            "Company": "Mynte",
            "Phone": "(858) 7447251",
            "Address1": "897 Ilene Plaza",
            "Address2": "0 Ryan Pass",
            "City": "Guamo",
            "Country": "Colombia",
            "Postcode": "733558",
            "Type": 3,
            "Status": 3,
            "DateCreated": "7\/7\/2018",
            "DateModified": "11\/15\/2018",
            "Position": 5,
            "ClientState": 3
        },
        {
            "ID": 659,
            "Name": "Ignace Daughtrey",
            "Company": "Innojam",
            "Phone": "(771) 1961054",
            "Address1": "5746 Warbler Street",
            "Address2": "98 Eliot Circle",
            "City": "Xiaoying",
            "Country": "China",
            "Type": 1,
            "Status": 1,
            "DateCreated": "8\/8\/2018",
            "DateModified": "10\/21\/2018",
            "Position": 5,
            "ClientState": 2
        },
        {
            "ID": 657,
            "Name": "Herculie Garthside",
            "Company": "Livefish",
            "Phone": "(682) 2767556",
            "Address1": "84709 Derek Lane",
            "Address2": "63424 Sutherland Crossing",
            "City": "Severo-Yeniseyskiy",
            "Country": "Russia",
            "Postcode": "192289",
            "Type": 3,
            "Status": 1,
            "DateCreated": "3\/21\/2019",
            "DateModified": "4\/21\/2018",
            "Position": 3,
            "ClientState": 1
        },
        {
            "ID": 688,
            "Name": "Ash Ingrem",
            "Company": "Eamia",
            "Phone": "(765) 1738916",
            "Address1": "3655 Prairie Rose Avenue",
            "Address2": "4 Victoria Hill",
            "City": "Mirkovci",
            "Country": "Croatia",
            "Postcode": "32100",
            "Type": 3,
            "Status": 2,
            "DateCreated": "11\/3\/2018",
            "DateModified": "9\/10\/2018",
            "Position": 6,
            "ClientState": 3
        },
        {
            "ID": 641,
            "Name": "Gustaf Fandrich",
            "Company": "Thoughtsphere",
            "Phone": "(116) 6197574",
            "Address1": "0553 Mayfield Hill",
            "Address2": "14315 Village Drive",
            "City": "Makiyivka",
            "Country": "Ukraine",
            "Type": 1,
            "Status": 3,
            "DateCreated": "11\/20\/2018",
            "DateModified": "5\/9\/2018",
            "Position": 2,
            "ClientState": 1
        },
        {
            "ID": 629,
            "Name": "Tony Shovell",
            "Company": "Eimbee",
            "Phone": "(745) 4025218",
            "Address1": "19183 Ilene Lane",
            "Address2": "2 Lakewood Trail",
            "City": "Strat\u00f3nion",
            "Country": "Greece",
            "Type": 1,
            "Status": 2,
            "DateCreated": "6\/3\/2018",
            "DateModified": "7\/26\/2018",
            "Position": 2,
            "ClientState": 3
        },
        {
            "ID": 630,
            "Name": "Teressa Trevascus",
            "Company": "Skyvu",
            "Phone": "(145) 4548710",
            "Address1": "68 Parkside Drive",
            "Address2": "72 Merrick Pass",
            "City": "Monte Novo",
            "State": "Set\u00fabal",
            "Country": "Portugal",
            "Postcode": "7540-051",
            "Type": 2,
            "Status": 1,
            "DateCreated": "6\/5\/2018",
            "DateModified": "9\/30\/2018",
            "Position": 1,
            "ClientState": 1
        }  
    ]
}